#!/bin/bash

apt install libgsl-dev wcslib-dev libcfitsio-dev
wget http://ftp.gnu.org/gnu/gnuastro/gnuastro-0.4.tar.gz
tar xf gnuastro-0.4.tar.gz   
cd gnuastro-0.4                  
./configure
make -j8           
make install
